### ISSUE TITLE
请问这是py的那个版本写的？

### ISSUE THREAD

**Issue by Jackxwb** [ruanluyu/FourierCircleDrawing#1]
请问这是py的那个版本写的？
先是报：SyntaxError: Non-ASCII character
后来查资料，在开头加入：# -*- coding: utf-8 -*
然后报：SyntaxError: invalid syntax

请问这是py的那个版本写的？py小白不太懂

**Comment by Jackxwb** [comment]
我的版本是 Python 3.7.0b4

**Comment by ruanluyu** [comment]
我的应该也是3.7，用vs下的py打开试试？

**Comment by Jackxwb** [comment]
电脑上没有vs，试了几个我电脑上有的Python，目前Python 3.4.6 编译通过。

其次，FourierCircleDrawing.pde编译失败，报错有两个：
报错1：
![image](https://user-images.githubusercontent.com/34720403/44733987-6282b500-ab1b-11e8-9f41-232143b164f5.png)
（貌似是文件无法读取，解决办法：换成绝对路径【注：路径中斜杠要换成双斜杠】）
报错2：
![image](https://user-images.githubusercontent.com/34720403/44734140-d45afe80-ab1b-11e8-8fb8-0f3cee7863ff.png)
（各种百度，好像是非xxx环境下不能设置屏幕尺寸？，解决办法：将设置屏幕大小的代码移动到外部）
【参考url：https://www.douban.com/group/topic/94760300/】
折腾了一晚终于用上了(●'◡'●)，希望有一天能搞懂原理o(^▽^)o

**Comment by ruanluyu** [comment]
解决就好，主要是pde那边官方还不成熟。所以工程路径经常出现问题，前几天我做了一个批处理install.bat，大家用这个部署工程processing就没问题了
